version: "2"

run:
  tests: true

linters:
  default: none
  enable:
    - bodyclose
    - errcheck
    - errorlint
    - gocritic
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused

  settings:
    revive:
      severity: warning
      rules:
        - name: indent-error-flow
        - name: empty-lines
        - name: early-return
        - name: if-return
        - name: range
        - name: superfluous-else
        - name: unnecessary-stmt
        - name: unexported-return

  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
